config/routes.rb
Rails.application.routes.draw do

  root to: 'sessions#new'

  get    'signup'  => 'users#new'
  get    'login'   => 'sessions#new'
  post   'login'   => 'sessions#create'
  delete 'logout'  => 'sessions#destroy'

  resources :users
  resources :cboxes, :only => [:show, :index]
  resources :installations

end

app/models/cbox.rb
class Cbox < ActiveRecord::Base

  has_one :installation
  has_one :user, through: :installation

  validates :serial, presence: true,
                     uniqueness: true
  
  validates :qrcode_url, presence: true
  

  before_validation(on: :create) do
    self.qrcode_url = "https://chart.googleapis.com/chart?cht=qr&&chs=128x128&chl=" + self.serial
  end



end

app/models/installation.rb
class Installation < ActiveRecord::Base

  attr_accessor :box_serial
  
  belongs_to :user
  belongs_to :cbox

  validates :user,  presence: true
  validates :box_serial, presence: true, on: :create
  validate :check_serial
  #validates :name,  presence: true

  before_save(on: :create) do
    self.name = self.name || "box_#{user.cboxes.size}"
  end

  def check_serial
    # return box_serial is not present, this case is asserted separately
    return unless box_serial.present?
    c = Cbox.find_by(:serial => box_serial)
    if c.blank?
      errors.add(:serial, "needs to be a valid number")
    elsif c.installation.present? && c.installation.id != self.id
      errors.add(:serial, "already assigned to an installation")
    else
     self.cbox = c
    end
  end

  def box_serial
    if self.cbox
      @box_serial ||= self.cbox.serial
    else
      @box_serial
    end
  end

end

app/models/user.rb
class User < ActiveRecord::Base

  has_many :installations
  has_many :cboxes, through: :installations

  VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i

  validates :name,  presence: true, length: { maximum: 50 }
  validates :email, presence: true, length: { maximum: 255 },
                    format: { with: VALID_EMAIL_REGEX },
                    uniqueness: { case_sensitive: false }

  before_save { self.email = email.downcase }

  has_secure_password  # This adds:
                       #    password_digest attribute
                       #    user.authenticate method (returns user if valid, false if not)
  validates :password, presence: true, length: { minimum: 6 }

  # Returns the hash digest of the given string.
  def User.digest(string)
    cost = ActiveModel::SecurePassword.min_cost ? BCrypt::Engine::MIN_COST :
        BCrypt::Engine.cost
    BCrypt::Password.create(string, cost: cost)
  end


end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  include SessionsHelper
end

app/controllers/cboxes_controller.rb
class CboxesController < ApplicationController

  def index
    @cboxes = Cbox.all
  end

  def show
    @cbox = Cbox.find(params[:id])
  end
 
 
end

app/controllers/installations_controller.rb
class InstallationsController < ApplicationController

  def index
    @installations = current_user.installations
  end

  def show
    @installation = Installation.find(params[:id])
  end

  # create a new Cbox
  def new
    @installation = Installation.new
  end

  def create
    @installation = Installation.new({user: current_user, box_serial: installation_params[:box_serial]})

    if @installation.save
      flash[:success] = "Box registered: #{@installation.name}"
      redirect_to current_user
    else
      # TODO flash error
      render 'new'
    end
  end

  def edit
    @installation = Installation.find(params[:id])
  end

  def update
    @installation = Installation.find(params[:id])
    if @installation.update_attributes(installation_params)
      flash[:success] = "Box updated: #{@installation.name}"
      redirect_to current_user
    else
      render 'edit'
    end
  end

  def destroy
  end

  private

  def installation_params
    params.require(:installation).permit(:name, :box_serial)
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
    redirect_to current_user if logged_in?
  end

  def create
    user = User.find_by(email: params[:session][:email].downcase)
    if user && user.authenticate(params[:session][:password])
      log_in user
      redirect_to user
    else
      flash.now[:danger] = 'Invalid email/password combination'
      render 'new'
    end
  end

  def destroy
    log_out
    redirect_to root_url
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  def index

  end

  def show
    @user = User.find(params[:id])
  end

  def new
    redirect_to current_user if logged_in?
    @user = User.new
  end

  def create
    @user = User.new(user_params)
    if @user.save
      flash[:success] = "Welcome!"
      log_in @user
      redirect_to @user
    else
      render 'new'
    end
  end

  private

  def user_params
    params.require(:user).permit(:name, :email, :password,
                                 :password_confirmation)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/cboxes_helper.rb
module CboxesHelper
end

app/helpers/installations_helper.rb
module InstallationsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
  # Logs in the given user.
  def log_in(user)
    session[:user_id] = user.id
  end

  def current_user
    @current_user ||= User.find_by(id: session[:user_id])
  end

  def logged_in?
    !current_user.nil?
  end

  def log_out
    session.delete(:user_id)
    @current_user = nil
  end

end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/cboxes/index.html.erb
<h3>Inventory of Manufactured Cboxes </h3>

<div class="cboxes-container">
	<%= render :partial => 'shared/cbox', :collection => @cboxes %>
</div>	



app/views/installations/_form.html.erb
<%
  submit_text = action_name == 'edit' ? 'Save' : 'Activate'
%>
<div class="cbox_form">
  <%= form_for @installation do |f| %>
    <%unless @installation.new_record? %>
      <div class="mdl-textfield mdl-js-textfield">
        <%= f.label :name, class:'mdl-textfield__label' %>
        <%= f.text_field :name ,class: 'mdl-textfield__input', required: true %>
      </div>
    <%end%>
    <div class="mdl-textfield mdl-js-textfield">
      <%= f.label :box_serial, class: 'mdl-textfield__label' %>
      <%= f.text_field :box_serial, class: 'mdl-textfield__input', required: true, disabled: !@installation.new_record? %>
    </div>

    <%= f.submit submit_text, class: "mdl-button mdl-js-button mdl-js-ripple-effect mdl-button--raised mdl-button--colored" %>
  <% end %>

</div>

app/views/installations/edit.html.erb
<div class="new_box_container card-container">
  <div class="mdl-card mdl-shadow--6dp">
    <div class="mdl-card__title mdl-color-text--white mdl-color--blue">
      <h2 class="mdl-card__title-text"><%= @installation.name %></h2>
    </div>
    <div class="mdl-card__supporting-text">
      <%= render partial: 'shared/error_messages', locals:{model: @installation}%>
    </div>
    <div class="mdl-card__actions">
      <%= render :partial=>'installations/form'%>
    </div>
  </div>
</div>

app/views/installations/new.html.erb
<div class="new_box_container card-container">
  <div class="mdl-card mdl-shadow--6dp">
    <div class="mdl-card__title mdl-color-text--white mdl-color--blue">
      <h2 class="mdl-card__title-text">Install Box</h2>
    </div>
    <div class="mdl-card__supporting-text">
      <!-- TODO print errors -->
      <%= render partial: 'shared/error_messages', locals:{model: @installation}%>
    </div>
    <div class="mdl-card__actions">
      <%= render :partial=>'installations/form'%>
    </div>
  </div>
</div>

app/views/installations/show.html.erb
<% provide(:title, @installation.name) %>

<div class="installation_show_container card-container">
  <div class="mdl-card mdl-shadow--6dp">
    <div class="mdl-card__title mdl-color-text--white mdl-color--blue">
      <h2 class="mdl-card__title-text"><%= @installation.name %></h2>
    </div>
    <div class="mdl-card__supporting-text">
      <ul class="mdl-list">
        <li class="mdl-list__item mdl-list__item--two-line">
          <span class="mdl-list__item-primary-content">
            <span><%= @installation.box_serial %></span>
            <span class="mdl-list__item-sub-title">Box Serial</span>
          </span>
          <span class="mdl-list__item-secondary-content">
            <img class="qrcode" src="<%= @installation.cbox.qrcode_url %> alt="QR code for serial <%=@installation.box_serial%>"> </img>
          </span>
        </li>
        <li class="mdl-list__item mdl-list__item--two-line">
          <span class="mdl-list__item-primary-content">
            <span>
              <%= @installation.created_at %>
            </span>
            <span class="mdl-list__item-sub-title">Created At</span>
          </span>
        </li>
        <li class="mdl-list__item mdl-list__item--two-line">
          <span class="mdl-list__item-primary-content">
            <span><%= @installation.updated_at %></span>
            <span class="mdl-list__item-sub-title">Last Updated</span>
          </span>
        </li>
      </ul>
    </div>
    <div class="mdl-card__actions mdl-card--border">
      <!-- Actions? -->
      <%= link_to "Edit", edit_installation_path(@installation),
                  class:'mdl-button mdl-button--colored mdl-js-button mdl-js-ripple-effect' %>
    </div>
  </div>
</div>

app/views/layouts/_header.html.erb
<header class="mdl-layout__header">
  <div class="mdl-layout__header-row">
    <!-- Title -->
    <span class="mdl-layout-title">BoxApp</span>
    <!-- Add spacer, to align navigation to the right -->
    <div class="mdl-layout-spacer"></div>
    <!-- Navigation. We hide it in small screens. -->
    <nav class="mdl-navigation mdl-layout--large-screen-only">
      <%= render :partial => 'layouts/menu' %>
    </nav>
  </div>
</header>
<div class="mdl-layout__drawer">
  <span class="mdl-layout-title">BoxApp</span>
  <nav class="mdl-navigation">
    <%= render :partial => 'layouts/menu' %>
  </nav>
</div>

app/views/layouts/_menu.html.erb
<%
  menu_item_class = "mdl-navigation__link mdl-typography--text-uppercase"
%>
<% if logged_in? %>
    <%= link_to "Profile", current_user, class: menu_item_class %>
    <%= link_to "Sign Out", logout_path, method: :delete, class: menu_item_class %>
<% else %>
    <%= link_to "Sign up", signup_path, class: menu_item_class %>
    <%= link_to "Log In", login_path, class: menu_item_class %>
<% end%>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Boxapp</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <link rel="stylesheet" href="https://fonts.googleapis.com/icon?family=Material+Icons">
  <%= csrf_meta_tags %>
</head>
<body>

<div class="mdl-layout mdl-js-layout mdl-layout--fixed-header">
  <%= render :partial => 'layouts/header'%>
  <div class="mdl-grid">
    <% flash.each do |message_type, message| %>
        <div class="mdl-cell mdl-cell--12-col">
          <div class="alert alert-<%= message_type %>"><%= message %></div>
        </div>
    <% end %>
  </div>
  <div class="mdl-grid main-grid">
    <main class="mdl-layout__content mdl-cell mdl-cell--middle">
      <div class="page-content">
        <%= yield %>
      </div>
    </main>
  </div>



  <!-- TODO move footer to partial -->
  <footer class="mdl-mini-footer">
    <div class="mdl-mini-footer__left-section">
      <div class="mdl-logo">BoxApp</div>
      <ul class="mdl-mini-footer__link-list">
        <li><a href="#">Help</a></li>
        <li><a href="#">Privacy & Terms</a></li>
      </ul>
    </div>
  </footer>

</div>


</body>
</html>

app/views/shared/_cbox.html.erb
<div id="cbox-<%=cbox.id %>" class="cbox <%= cbox.installation.present? ? 'registered' : '' %>">
	<img class="qrcode" src=<%=cbox.qrcode_url%> alt="QR code for serial <%=cbox.serial%>"> </img>
	<div class="serial">
		<%= cbox.serial %>
	</div>
</div>

app/views/shared/_error_messages.html.erb
<% if model.errors.any? %>
    <div id="error_explanation">
      <div class="alert alert-danger">
        The form contains <%= pluralize(model.errors.count, "error") %>.
      </div>
      <ul>
        <% model.errors.full_messages.each do |msg| %>
            <li><%= msg %></li>
        <% end %>
      </ul>
    </div>
<% end %>

app/views/users/new.html.erb
<% provide(:title, 'Sign up') %>

<div class="card-container">
  <div class="mdl-card mdl-shadow--6dp">
    <div class="mdl-card__title">
      <h2 class="mdl-card__title-text">Sign up</h2>
    </div>
    <div class="mdl-card__supporting-text">
      <%= render partial: 'shared/error_messages', locals:{model: @user}%>
    </div>
    <div class="mdl-card__actions">
      <%= form_for(@user) do |f| %>
          <div class="mdl-textfield mdl-js-textfield">
            <%= f.label :name, class: 'mdl-textfield__label' %>
            <%= f.text_field :name, class: 'mdl-textfield__input', required: true %>
          </div>

          <div class="mdl-textfield mdl-js-textfield">
            <%= f.label :email, class: 'mdl-textfield__label' %>
            <%= f.email_field :email, class: 'mdl-textfield__input',required: true %>
          </div>

          <div class="mdl-textfield mdl-js-textfield">
            <%= f.label :password, class: 'mdl-textfield__label' %>
            <%= f.password_field :password, class: 'mdl-textfield__input',required: true %>
          </div>

          <div class="mdl-textfield mdl-js-textfield">
            <%= f.label :password_confirmation, "Confirmation", class: 'mdl-textfield__label' %>
            <%= f.password_field :password_confirmation, class: 'mdl-textfield__input',required: true %>
          </div>


          <%= f.submit "Create my account", class: "mdl-button mdl-js-button mdl-button--raised mdl-button--colored" %>
      <% end %>
    </div>
  </div>
</div>

app/views/users/show.html.erb
<% provide(:title, "My installations") %>

<div class="mdl-grid">
  <div class="mdl-cell mdl-cell--10-col">
    <h2>
      <%= "My Installations" %>
    </h2>
  </div>
  <div class="mdl-cell mdl-cell--2-col">

    <h3>
      <%= current_user.name%>
    </h3>
    <%= current_user.email %>
  </div>

</div>

<div class="mdl-grid">
  <div class="mdl-cell mdl-cell--6-col">

    <ul class="mdl-list">
      <% current_user.installations.each do |installation|%>
        <li class="mdl-list__item mdl-list__item--two-line">
          <span class="mdl-list__item-primary-content">
            <i class="material-icons mdl-list__item-avatar">explore</i>
            <span><%=link_to installation.name, installation, class: '' %></span>
            <span class="mdl-list__item-sub-title"><%= installation.cbox.serial %></span>
          </span>
          <span class="mdl-list__item-secondary-content">
            <span class="mdl-list__item-secondary-info">Edit</span>
            <%= link_to edit_installation_path(installation), class:'mdl-list__item-secondary-action'  do %>
              <i class="material-icons">settings</i>
            <% end %>
          </span>
        </li>
      <% end %>
    </ul>
  </div>
</div>
<div class="mdl-grid">
  <div class="mdl-cell mdl-cell--1-col">
    <%= link_to(new_installation_path, id: 'new_box', class: 'mdl-button mdl-js-button mdl-button--fab mdl-js-ripple-effect mdl-button--colored mdl-shadow--6dp')do %>
        <i class="material-icons">add</i>
    <%end%>
    <div class="mdl-tooltip" for="new_box">
      Add a box
    </div>
  </div>
</div>